// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay.proto

package relay_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD_TYPE int32

const (
	CMD_TYPE_CMD_DATA CMD_TYPE = 1
	CMD_TYPE_CMD_PAD  CMD_TYPE = 2
	CMD_TYPE_CMD_AUTH CMD_TYPE = 3
)

var CMD_TYPE_name = map[int32]string{
	1: "CMD_DATA",
	2: "CMD_PAD",
	3: "CMD_AUTH",
}
var CMD_TYPE_value = map[string]int32{
	"CMD_DATA": 1,
	"CMD_PAD":  2,
	"CMD_AUTH": 3,
}

func (x CMD_TYPE) Enum() *CMD_TYPE {
	p := new(CMD_TYPE)
	*p = x
	return p
}
func (x CMD_TYPE) String() string {
	return proto.EnumName(CMD_TYPE_name, int32(x))
}
func (x *CMD_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_TYPE_value, data, "CMD_TYPE")
	if err != nil {
		return err
	}
	*x = CMD_TYPE(value)
	return nil
}
func (CMD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_relay_976d75d130024ac7, []int{0}
}

type RelayPacket struct {
	RndPadFront          []byte   `protobuf:"bytes,1,opt,name=rnd_pad_front,json=rndPadFront" json:"rnd_pad_front,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Cmd                  *int32   `protobuf:"varint,3,opt,name=cmd" json:"cmd,omitempty"`
	RndPadEnd            []byte   `protobuf:"bytes,10,opt,name=rnd_pad_end,json=rndPadEnd" json:"rnd_pad_end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayPacket) Reset()         { *m = RelayPacket{} }
func (m *RelayPacket) String() string { return proto.CompactTextString(m) }
func (*RelayPacket) ProtoMessage()    {}
func (*RelayPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_976d75d130024ac7, []int{0}
}
func (m *RelayPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayPacket.Unmarshal(m, b)
}
func (m *RelayPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayPacket.Marshal(b, m, deterministic)
}
func (dst *RelayPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayPacket.Merge(dst, src)
}
func (m *RelayPacket) XXX_Size() int {
	return xxx_messageInfo_RelayPacket.Size(m)
}
func (m *RelayPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayPacket.DiscardUnknown(m)
}

var xxx_messageInfo_RelayPacket proto.InternalMessageInfo

func (m *RelayPacket) GetRndPadFront() []byte {
	if m != nil {
		return m.RndPadFront
	}
	return nil
}

func (m *RelayPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *RelayPacket) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *RelayPacket) GetRndPadEnd() []byte {
	if m != nil {
		return m.RndPadEnd
	}
	return nil
}

type RelayAuthReq struct {
	User                 *string  `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Pwd                  *string  `protobuf:"bytes,2,opt,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayAuthReq) Reset()         { *m = RelayAuthReq{} }
func (m *RelayAuthReq) String() string { return proto.CompactTextString(m) }
func (*RelayAuthReq) ProtoMessage()    {}
func (*RelayAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_976d75d130024ac7, []int{1}
}
func (m *RelayAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayAuthReq.Unmarshal(m, b)
}
func (m *RelayAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayAuthReq.Marshal(b, m, deterministic)
}
func (dst *RelayAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayAuthReq.Merge(dst, src)
}
func (m *RelayAuthReq) XXX_Size() int {
	return xxx_messageInfo_RelayAuthReq.Size(m)
}
func (m *RelayAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_RelayAuthReq proto.InternalMessageInfo

func (m *RelayAuthReq) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

func (m *RelayAuthReq) GetPwd() string {
	if m != nil && m.Pwd != nil {
		return *m.Pwd
	}
	return ""
}

type RelayAuthRsp struct {
	Result               *int32   `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	Errmsg               *string  `protobuf:"bytes,2,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayAuthRsp) Reset()         { *m = RelayAuthRsp{} }
func (m *RelayAuthRsp) String() string { return proto.CompactTextString(m) }
func (*RelayAuthRsp) ProtoMessage()    {}
func (*RelayAuthRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_976d75d130024ac7, []int{2}
}
func (m *RelayAuthRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayAuthRsp.Unmarshal(m, b)
}
func (m *RelayAuthRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayAuthRsp.Marshal(b, m, deterministic)
}
func (dst *RelayAuthRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayAuthRsp.Merge(dst, src)
}
func (m *RelayAuthRsp) XXX_Size() int {
	return xxx_messageInfo_RelayAuthRsp.Size(m)
}
func (m *RelayAuthRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayAuthRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RelayAuthRsp proto.InternalMessageInfo

func (m *RelayAuthRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *RelayAuthRsp) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*RelayPacket)(nil), "relay.msg.RelayPacket")
	proto.RegisterType((*RelayAuthReq)(nil), "relay.msg.RelayAuthReq")
	proto.RegisterType((*RelayAuthRsp)(nil), "relay.msg.RelayAuthRsp")
	proto.RegisterEnum("relay.msg.CMD_TYPE", CMD_TYPE_name, CMD_TYPE_value)
}

func init() { proto.RegisterFile("relay.proto", fileDescriptor_relay_976d75d130024ac7) }

var fileDescriptor_relay_976d75d130024ac7 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x41, 0x4b, 0xf4, 0x30,
	0x10, 0x86, 0xe9, 0xf6, 0xdb, 0x4f, 0x3b, 0xa9, 0x50, 0xe6, 0x20, 0x3d, 0xc9, 0xd2, 0xd3, 0xe2,
	0xc1, 0x8b, 0x9e, 0x85, 0x60, 0x57, 0xbc, 0x08, 0x25, 0xd4, 0x83, 0xa7, 0x12, 0x76, 0xe2, 0x0a,
	0x6e, 0xd3, 0x3a, 0x49, 0x59, 0xfc, 0xf7, 0x92, 0xb4, 0x0b, 0xde, 0x9e, 0x67, 0x26, 0xf3, 0xbe,
	0x01, 0xc1, 0xe6, 0xa8, 0x7f, 0xee, 0x46, 0x1e, 0xfc, 0x80, 0xd9, 0x2c, 0xbd, 0x3b, 0x54, 0x27,
	0x10, 0x2a, 0x48, 0xa3, 0xf7, 0x5f, 0xc6, 0x63, 0x05, 0x57, 0x6c, 0xa9, 0x1b, 0x35, 0x75, 0x1f,
	0x3c, 0x58, 0x5f, 0x26, 0x9b, 0x64, 0x9b, 0x2b, 0xc1, 0x96, 0x1a, 0x4d, 0xcf, 0x61, 0x84, 0x08,
	0xff, 0x48, 0x7b, 0x5d, 0xae, 0xe2, 0x2a, 0x32, 0x16, 0x90, 0xee, 0x7b, 0x2a, 0xd3, 0x4d, 0xb2,
	0x5d, 0xab, 0x80, 0x78, 0x03, 0xe2, 0x9c, 0x64, 0x2c, 0x95, 0x10, 0x1f, 0x67, 0x73, 0xce, 0xce,
	0x52, 0xf5, 0x00, 0x79, 0x2c, 0x96, 0x93, 0xff, 0x54, 0xe6, 0x3b, 0xa4, 0x4e, 0xce, 0x70, 0x2c,
	0xcc, 0x54, 0xe4, 0x90, 0x3a, 0x9e, 0x28, 0x16, 0x65, 0x2a, 0x60, 0xf5, 0xf8, 0xf7, 0xca, 0x8d,
	0x78, 0x0d, 0xff, 0xd9, 0xb8, 0xe9, 0x38, 0x7f, 0x74, 0xad, 0x16, 0x0b, 0x73, 0xc3, 0xdc, 0xbb,
	0xc3, 0x72, 0xbc, 0xd8, 0xed, 0x3d, 0x5c, 0x3e, 0xbd, 0xd6, 0x5d, 0xfb, 0xde, 0xec, 0x30, 0x9f,
	0xb9, 0x96, 0xad, 0x2c, 0x12, 0x14, 0x70, 0x11, 0xac, 0x91, 0x75, 0xb1, 0x3a, 0xaf, 0xe4, 0x5b,
	0xfb, 0x52, 0xa4, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x36, 0xea, 0x61, 0x17, 0x3c, 0x01, 0x00,
	0x00,
}
