// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relay.proto

package relay_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CMD_TYPE int32

const (
	CMD_TYPE_CMD_DATA CMD_TYPE = 1
	CMD_TYPE_CMD_PAD  CMD_TYPE = 2
)

var CMD_TYPE_name = map[int32]string{
	1: "CMD_DATA",
	2: "CMD_PAD",
}
var CMD_TYPE_value = map[string]int32{
	"CMD_DATA": 1,
	"CMD_PAD":  2,
}

func (x CMD_TYPE) Enum() *CMD_TYPE {
	p := new(CMD_TYPE)
	*p = x
	return p
}
func (x CMD_TYPE) String() string {
	return proto.EnumName(CMD_TYPE_name, int32(x))
}
func (x *CMD_TYPE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CMD_TYPE_value, data, "CMD_TYPE")
	if err != nil {
		return err
	}
	*x = CMD_TYPE(value)
	return nil
}
func (CMD_TYPE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_relay_095d9d29e185d739, []int{0}
}

type RelayMsg struct {
	Rnd                  []byte   `protobuf:"bytes,1,opt,name=rnd" json:"rnd,omitempty"`
	Body                 []byte   `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
	Crc32                *uint32  `protobuf:"varint,3,opt,name=crc32" json:"crc32,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayMsg) Reset()         { *m = RelayMsg{} }
func (m *RelayMsg) String() string { return proto.CompactTextString(m) }
func (*RelayMsg) ProtoMessage()    {}
func (*RelayMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_095d9d29e185d739, []int{0}
}
func (m *RelayMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayMsg.Unmarshal(m, b)
}
func (m *RelayMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayMsg.Marshal(b, m, deterministic)
}
func (dst *RelayMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayMsg.Merge(dst, src)
}
func (m *RelayMsg) XXX_Size() int {
	return xxx_messageInfo_RelayMsg.Size(m)
}
func (m *RelayMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayMsg.DiscardUnknown(m)
}

var xxx_messageInfo_RelayMsg proto.InternalMessageInfo

func (m *RelayMsg) GetRnd() []byte {
	if m != nil {
		return m.Rnd
	}
	return nil
}

func (m *RelayMsg) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *RelayMsg) GetCrc32() uint32 {
	if m != nil && m.Crc32 != nil {
		return *m.Crc32
	}
	return 0
}

type RelayBody struct {
	Cmd                  *int32   `protobuf:"varint,1,opt,name=cmd" json:"cmd,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RelayBody) Reset()         { *m = RelayBody{} }
func (m *RelayBody) String() string { return proto.CompactTextString(m) }
func (*RelayBody) ProtoMessage()    {}
func (*RelayBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_relay_095d9d29e185d739, []int{1}
}
func (m *RelayBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelayBody.Unmarshal(m, b)
}
func (m *RelayBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelayBody.Marshal(b, m, deterministic)
}
func (dst *RelayBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelayBody.Merge(dst, src)
}
func (m *RelayBody) XXX_Size() int {
	return xxx_messageInfo_RelayBody.Size(m)
}
func (m *RelayBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RelayBody.DiscardUnknown(m)
}

var xxx_messageInfo_RelayBody proto.InternalMessageInfo

func (m *RelayBody) GetCmd() int32 {
	if m != nil && m.Cmd != nil {
		return *m.Cmd
	}
	return 0
}

func (m *RelayBody) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RelayMsg)(nil), "relay.msg.RelayMsg")
	proto.RegisterType((*RelayBody)(nil), "relay.msg.RelayBody")
	proto.RegisterEnum("relay.msg.CMD_TYPE", CMD_TYPE_name, CMD_TYPE_value)
}

func init() { proto.RegisterFile("relay.proto", fileDescriptor_relay_095d9d29e185d739) }

var fileDescriptor_relay_095d9d29e185d739 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0xcd, 0x49,
	0xac, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x70, 0x72, 0x8b, 0xd3, 0x95, 0x4c,
	0xb8, 0x38, 0x82, 0x40, 0x1c, 0xdf, 0xe2, 0x74, 0x21, 0x6e, 0x2e, 0xe6, 0xa2, 0xbc, 0x14, 0x09,
	0x46, 0x05, 0x46, 0x0d, 0x1e, 0x21, 0x1e, 0x2e, 0x96, 0xa4, 0xfc, 0x94, 0x4a, 0x09, 0x26, 0x30,
	0x8f, 0x97, 0x8b, 0x35, 0xb9, 0x28, 0xd9, 0xd8, 0x48, 0x82, 0x59, 0x81, 0x51, 0x83, 0x57, 0x49,
	0x8d, 0x8b, 0x13, 0xac, 0xcb, 0x29, 0x3f, 0xa5, 0x12, 0xa4, 0x2d, 0x39, 0x17, 0xa2, 0x8d, 0x15,
	0xa4, 0x2d, 0x25, 0xb1, 0x24, 0x11, 0xa2, 0x4d, 0x4b, 0x95, 0x8b, 0xc3, 0xd9, 0xd7, 0x25, 0x3e,
	0x24, 0x32, 0xc0, 0x55, 0x88, 0x07, 0xc2, 0x76, 0x71, 0x0c, 0x71, 0x14, 0x60, 0x14, 0xe2, 0xe6,
	0x62, 0x07, 0xf1, 0x02, 0x1c, 0x5d, 0x04, 0x98, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0x2a,
	0x61, 0xef, 0x9d, 0x00, 0x00, 0x00,
}
